name: pytest workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pybuildjob1:
    runs-on: ubuntu-latest
    steps:
      - name: pybuildstep1
        uses: actions/checkout@v4
        
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: run python command 
        run: pip install -r requirements.txt

      - name: Executing
        run: pytest -v
        continue-on-error: true
      
      - name: checking
        run: echo "helo"
      
      - name: buikd docker image
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      
      - name: build docker image
        run: |
          set -x
          docker version
          docker build -t pydoc .
        

